Sync with internal repo
Samsung/LPVS pull request #190
Opened 2023-07-26 14:14 UTC by m-rudyk

# Description

This pull request aims to create a reusable package, promoting code modularity and easier integration across projects.
Synchronize open-source and internal LPVS versions, ensuring consistency and improved collaboration between the two environments.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# How Has This Been Tested?
Deploy and test localy. 

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-07-27 05:40 UTC, tiokim commented
Thanks for opening this PR. Can you break this down in multiple PRs for reviewing and approving them easily?

2023-07-27 06:51 UTC, o-kopysov commented on src/main/java/com/lpvs/service/LPVSGitHubService.java
> +                        commitComment + "\n\n###### <p align='right'>Check the validation details on [SOSHUB LPVS](" +
SOSHUB is an internal system and should be deleted from this repo.

2023-07-27 06:52 UTC, o-kopysov commented on src/main/java/com/lpvs/service/LPVSGitHubService.java
> +                        commitComment + "\n\n###### <p align='right'>Check the validation details on [SOSHUB LPVS](" +
SOSHUB is an internal system and should be deleted from this repo.

2023-08-15 14:08 UTC, o-kopysov approved these changes
LGTM

2023-08-16 00:13 UTC, tiokim requested changes
PTAL

2023-08-16 00:13 UTC, tiokim commented on src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
> +    FAST_SCAN("fast_scan");
I don't know why we need these enums.

2023-08-16 00:13 UTC, tiokim commented on src/main/java/com/lpvs/service/LPVSGitHubService.java
> +            if (System.getenv("LPVS_GITHUB_TOKEN") != null) GITHUB_AUTH_TOKEN = System.getenv("LPVS_GITHUB_TOKEN");
Please check the indentation.

2023-08-16 09:51 UTC, v-kerimov approved these changes

2023-08-16 12:35 UTC, m-rudyk commented on src/main/java/com/lpvs/entity/enums/LPVSPullRequestAction.java
> +    FAST_SCAN("fast_scan");
you are right, thank you.

2023-08-17 01:04 UTC, tiokim approved these changes
LGTM!

2023-08-17 05:10 UTC, merged