frontend home page
Samsung/LPVS pull request #204
Opened 2023-09-02 08:43 UTC by kyudori

# Description

LPVS Front-End Home Page.
User, History, and Dashboard pages will be uploaded.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [ ] Test Coverage update

# How Has This Been Tested?
$npm install
$npm start
Go to http://localhost:3000 with Chrome.
![image](https://github.com/Samsung/LPVS/assets/57388014/f542f5d5-cea9-46c2-a3d7-1895663c63f5)

**Test Configuration**:
* Java: v11
* LPVS Release: v1.1.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-09-03 11:01 UTC, o-kopysov approved these changes
LGTM

2023-09-03 19:53 UTC, m-rudyk commented on frontend/.env
> +REACT_APP_KAKAO_REST_API_KEY={type_your_key}
It is better to add empty line at the end of file here and few other places in this PR.

2023-09-03 19:57 UTC, o-kopysov commented
Also I recommend to add file headers into the files with source code.

2023-09-03 23:02 UTC, tiokim commented
> Also I recommend to add file headers into the files with source code.

Do you mean copyright/license header?

2023-09-04 03:41 UTC, o-kopysov commented
> Do you mean copyright/license header?

Yes, exactly.

2023-09-04 14:02 UTC, o-kopysov approved these changes
LGTM

2023-09-04 14:42 UTC, tiokim requested changes

2023-09-04 14:42 UTC, tiokim commented on frontend/public/index.html
> +
It should be commented out.

2023-09-04 14:51 UTC, kyudori commented on frontend/public/index.html
> +
Done.

2023-09-04 14:52 UTC, tiokim approved these changes
LGTM

2023-09-04 14:57 UTC, merged