add tests for entity/LPVSLicense
Samsung/LPVS pull request #21
Opened 2022-08-17 12:38 UTC by csvitschool

# Description
Added unit test set for the LPVSLicense class. This step is required for the GitHub action infra setup.
Fixes # (issue)

## Type of change

- [x] Test Coverage update

# How Has This Been Tested?

**Test Configuration**:
* Java: v18
* LPVS Release: v1.x.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-08-17 16:37 UTC, o-kopysov requested changes
Please check my comment

2022-08-17 16:37 UTC, o-kopysov commented on src/test/java/com/lpvs/entity/LPVSLicenseTest.java
> +//        assertIterableEquals(lpvsLicenseBase.getIncompatibleWith(), baseIncompatibleWith);
I checked we do not use the constructor `new LPVSLicense(lpvsLicense)` in the code. 
So please:
1. Remove this constructor from the file `\src\main\java\com\lpvs\entity\LPVSLicense.java`
2. Replace the constructor in your unit test with this one:
`LPVSLicense(Long licenseId, String licenseName, String spdxId, String access, String checklistUrl, List<String> incompatibleWith)`

2022-08-17 22:50 UTC, MoonkiHong reviewed
Please take a look at my comment.

2022-08-17 22:50 UTC, MoonkiHong commented on src/test/java/com/lpvs/entity/LPVSLicenseTest.java
> +
Do we need a blank line here? 🙏

2022-08-18 14:14 UTC, o-kopysov commented on src/test/java/com/lpvs/entity/LPVSLicenseTest.java
> +        Long newActualValue = 0L;
Please use long instead of Long

2022-08-18 14:14 UTC, o-kopysov commented on src/test/java/com/lpvs/entity/LPVSLicenseTest.java
> +    final Long baseLicenseId = 1234567890L;
Please use long instead of Long

2022-08-18 14:15 UTC, o-kopysov requested changes
Please check my comments.
Also please remove the unused constructor from `\src\main\java\com\lpvs\entity\LPVSLicense.java`

2022-08-19 06:35 UTC, o-kopysov approved these changes
Perfect. Thank you for your great job!

2022-08-19 06:37 UTC, merged