Added new tests for LPVSScanossDetectService, LPVSStatisticsService
Samsung/LPVS pull request #260
Opened 2023-10-24 14:27 UTC by v-kerimov

# Description

Added new tests to increase test coverage.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Code cleanup/refactoring
- [ ] Documentation update
- [ ] This change requires a documentation update
- [ ] CI system update
- [x] Test Coverage update

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration. Below is just an example and you can delete it when you contribute.

**Test Configuration**:
* Java: v11
* LPVS Release: v1.x.x

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-10-24 14:52 UTC, o-kopysov commented on src/test/java/com/lpvs/service/scanner/scanoss/LPVSScanossDetectServiceTest.java
> +            setSpdxId("MIT");
This test is fixed in my PR #258 
Please exclude it from your PR.

2023-10-24 14:56 UTC, o-kopysov requested changes
Please check #258 and fix LPVSScanossDetectServiceTest.java accordingly.

2023-10-25 08:12 UTC, o-kopysov commented on src/test/java/com/lpvs/service/LPVSStatisticsServiceTest.java
> +        assertEquals(0, result.size());*/
Do we need this commented code?

2023-10-25 08:13 UTC, o-kopysov reviewed
@v-kerimov  Why did you delete new tests from LPVSScanossDetectService?

2023-10-25 10:17 UTC, o-kopysov approved these changes
Additional UT is added to PR #265. Approved.

2023-10-25 10:22 UTC, tdrozdovsky approved these changes

2023-10-25 10:31 UTC, merged